### PR TITLE
package.json: remove wrong keywords (copy/pasted from Nat)

### PR DESCRIPTION
**Pull request by warner**
@katelynsills is there an "official" list of keywords anywhere, or is it a folksonomy? Not sure what we should have for MakeHardener but probably not `integer overflow` :).

### CODE REVIEW

**Comment by katelynsills** [comment]
I think it's a folksonomy. This definitely needed fixing!

**Comment by katelynsills** [comment]
Whoops, sorry, didn't mean to merge. I got trigger happy after all the ESLint merges.

**Comment by erights** [comment]
What does a "keywords" section in a package.json mean?

**Comment by katelynsills** [comment]
It shows up on the [npm page for the package](https://www.npmjs.com/package/@agoric/harden) like this:
screen shot 2019-02-23 at 11 35 51 am

This is from the `harden` npm page, which has the same issue.

**Pull request merged**
